---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-devops-proj
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-devops-proj
  template:
    metadata:
      labels:
        app: aws-devops-proj
    spec:
      containers:
      - name: aws-devops-container
        image: engineerhaider/aws-devops-proj:latest
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20